# 错误处理

## error接口

go中使用error接口，进行普通错误处理。error是内置接口，故error类型也是一种内置数据类型———错误类型。

## 创建错误类型值

error接口实现的只是一种内置数据类型，可存入的数据值可以由用户自己创建。

### errors包函数New()

errors库提供了错误的创建函数。

    var e error
    e = errors.New("这是一个自己的错误")
或者

    e:=errors.New("这是一个自己的错误")
打印并查看运行结果

    fmt.Println(e)
    //errors:错误

### fmt包函数Errorf()

格式化输出包中的库函数也可以输出错误

    e2 := fmt.Errorf("test:%s", "fmt：错误")
打印并查看运行结果

    test:fmt：错误

### 总结

通过查看源码，可以发现fmt实际调用的就是error的New(),但更加强大一些：加入了格式化输出功能。

    func Errorf(format string, a ...interface{}) error {
        return errors.New(Sprintf(format, a...))
    }

## error接口应用

实例：除法函数，除数为0报错

    func MyDiv(a, b int) (result int, err error) {
        if b == 0 {
            err = errors.New("除数不能为0")
        } else {
            result = a / b
        }
        return
    }

调用除法函数

    result, err := MyDiv(5, 0)
        if err != nil {
            fmt.Println(err)
        } else {
            fmt.Println(result)
        }

结果:

    除数不能为0

## panic()和recover()

显式调用panic可中断函数的执行，进而中断整个程序，比error要强硬

    panic("panic test")
    //参数为空接口类型

而recover函数能在panic发生后，恢复现场,panic信息转换为error变量并作为返回值去处理，让整个程序得以继续执行。

    defer func() {
        if err := recover(); err != nil {
            fmt.Println(err)
        }
    }() //调用一下
    var b [10]int
    b[x] = 8888

注意事项

1. recover()必须与**defer连用**，在函数中断前的最后时刻执行。
2. recover()必须放到一个**匿名函数内**部执行，否则无效